global:
    metacalibration: True
CLPFirecrown:
    hmf: 'despali16'
    min_mass: 13.0
    max_mass: 16.0
    min_z: 0.2
    max_z: 0.8
    pivot_mass: 14.243956661092533
    pivot_z: 0.15
    survey_name: 'SDSSCluster_redshift_richness'
    sampler: 'emcee'
    use_completeness: false
    use_purity: false
    use_cluster_counts: True
    use_mean_log_mass: True
    emcee_walkers: 100
    emcee_samples: 50000
    emcee_nsteps: 20
    cosmological_parameters:
        omega_c: {'sample': True, 'values': [0.1552, 0.2052, 0.3552]}
        sigma_8: {'sample': True, 'values': [0.7, 0.800, 0.9]}
    firecrown_parameters:
        mass_distribution_mu0: {'sample': True, 'values': [2.0, 3.0, 4.0]}
        mass_distribution_mu1: {'sample': True, 'values': [0.4, 0.8, 1.2]}
        mass_distribution_mu2: {'sample': True, 'values': [-0.6, -0.3, 0.6]}
        mass_distribution_sigma0: {'sample': True, 'values': [0.02, 0.3, 0.6]}
        mass_distribution_sigma1: {'sample': True, 'values': [-0.1, -0.03, 0.1]}
        mass_distribution_sigma2: {'sample': True, 'values': [-0.1, 0.06, 0.1]}
